---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: debian-7.6
  - name: debian-6.0.10
  - name: centos-6.5
  - name: macosx-10.8
  - name: macosx-10.9
  - name: macosx-10.10
  - name: windows-2012r2
    driver:
      box: kensykora/windows_2012_r2_standard

suites:
  - name: default
    run_list:
      - recipe[chef-dk]
  - name: global_shell_init
    run_list:
      - recipe[chef-dk]
    attributes:
      chef_dk:
        global_shell_init: true
    excludes:
      - windows-2012r2
  - name: install_from_specific_url
    run_list:
      - recipe[chef-dk]
    attributes:
      chef_dk:
        package_url: https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chefdk_0.3.4-1_amd64.deb
    excludes:
      - ubuntu-12.04
      - debian-7.6
      - debian-6.0.10
      - centos-6.5
      - macosx-10.8
      - macosx-10.9
      - ubuntu.12.04
      - debian-7.1.0
      - centos-6.4
      - windows-2012r2
